# Generated by Django 6.0.5 on 2026-05-08 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_utilise', models.CharField(blank=True, max_length=100)),
                ('date_courrier', models.DateField(blank=True, null=True)),
                ('numero_dossier', models.CharField(max_length=100, unique=True)),
                ('numero_fase', models.CharField(blank=True, max_length=100)),
                ('nom_ecole', models.CharField(max_length=255)),
                ('lieu_ecole', models.CharField(blank=True, max_length=255)),
                ('nom_parent', models.CharField(max_length=150)),
                ('prenom_parent', models.CharField(blank=True, max_length=150)),
                ('nom_enfant', models.CharField(blank=True, max_length=150)),
                ('prenom_enfant', models.CharField(blank=True, max_length=150)),
                ('genre_enfant', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('autre', 'Autre')], max_length=20)),
                ('personnel_concerne', models.CharField(blank=True, max_length=255)),
                ('motif_plainte', models.TextField()),
                ('personne_traitant_dossier', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('traitee', 'Traitée'), ('archivee', 'Archivée')], default='nouvelle', max_length=20)),
                ('retour_wf_signe', models.BooleanField(default=False)),
                ('remarque', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plainte',
                'verbose_name_plural': 'Plaintes',
                'ordering': ['-cree_le'],
            },
        ),
    ]
