# Generated by Django 6.0.5 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaintes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plainte',
            name='nom_feminin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='plainte',
            name='nom_masculin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='plainte',
            name='retour_wf_signe_le',
            field=models.DateField(blank=True, null=True),
        ),
    ]
