from django.core.management.base import BaseCommand

from plaintes.models import Plainte


class Command(BaseCommand):
    help = 'Crée des plaintes fictives pour tester l’application.'

    def handle(self, *args, **options):
        plaintes = [
            {
                'numero_dossier': 'DOS-2026-001',
                'numero_fase': 'FASE-1001',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'École communale du Centre',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Dupont',
                'prenom_parent': 'Marie',
                'nom_enfant': 'Dupont',
                'prenom_enfant': 'Lucas',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le suivi administratif du dossier.',
                'personne_traitant_dossier': 'Lucas',
                'statut': Plainte.STATUT_NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Dossier fictif pour test.',
            },
            {
                'numero_dossier': 'DOS-2026-002',
                'numero_fase': 'FASE-1002',
                'canal_utilise': 'Email',
                'nom_ecole': 'Institut Saint-Pierre',
                'lieu_ecole': 'Liège',
                'nom_parent': 'Martin',
                'prenom_parent': 'Sophie',
                'nom_enfant': 'Martin',
                'prenom_enfant': 'Emma',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant une communication insuffisante avec les parents.',
                'personne_traitant_dossier': 'Maurice',
                'statut': Plainte.STATUT_EN_COURS,
                'retour_wf_signe': True,
                'remarque': 'À vérifier avec la direction.',
            },
            {
                'numero_dossier': 'DOS-2026-003',
                'numero_fase': 'FASE-1003',
                'canal_utilise': 'Téléphone',
                'nom_ecole': 'Athénée Royal Nord',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Bernard',
                'prenom_parent': 'Ahmed',
                'nom_enfant': 'Bernard',
                'prenom_enfant': 'Nora',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Éducateur',
                'motif_plainte': 'Plainte concernant un incident survenu pendant la récréation.',
                'personne_traitant_dossier': 'Nadine',
                'statut': Plainte.STATUT_EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'Attente de documents complémentaires.',
            },
            {
                'numero_dossier': 'DOS-2026-004',
                'numero_fase': 'FASE-1004',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'École Les Tilleuls',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Lambert',
                'prenom_parent': 'Claire',
                'nom_enfant': 'Lambert',
                'prenom_enfant': 'Hugo',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Secrétariat',
                'motif_plainte': 'Plainte relative à une erreur dans un document scolaire.',
                'personne_traitant_dossier': 'Maurice',
                'statut': Plainte.STATUT_TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Dossier traité.',
            },
            {
                'numero_dossier': 'DOS-2026-005',
                'numero_fase': 'FASE-1005',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'Collège Sainte-Marie',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Petit',
                'prenom_parent': 'Nadia',
                'nom_enfant': 'Petit',
                'prenom_enfant': 'Yanis',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le délai de réponse à une demande parentale.',
                'personne_traitant_dossier': 'Nadine',
                'statut': Plainte.STATUT_ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Archive fictive.',
            },
            {
                'numero_dossier': 'DOS-2026-006',
                'numero_fase': 'FASE-1006',
                'canal_utilise': 'Email',
                'nom_ecole': 'École du Parc',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Morel',
                'prenom_parent': 'Julien',
                'nom_enfant': 'Morel',
                'prenom_enfant': 'Lina',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une difficulté de communication avec l’établissement.',
                'personne_traitant_dossier': 'Agent Dupuis',
                'statut': Plainte.STATUT_NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Nouvelle plainte fictive.',
            },
            {
                'numero_dossier': 'DOS-2026-007',
                'numero_fase': 'FASE-1007',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Institut Notre-Dame',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Lefevre',
                'prenom_parent': 'Amélie',
                'nom_enfant': 'Lefevre',
                'prenom_enfant': 'Noah',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant le suivi pédagogique de l’enfant.',
                'personne_traitant_dossier': 'Gestionnaire Moreau',
                'statut': Plainte.STATUT_EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'Analyse du dossier en cours.',
            },
            {
                'numero_dossier': 'DOS-2026-008',
                'numero_fase': 'FASE-1008',
                'canal_utilise': 'Téléphone',
                'nom_ecole': 'École Saint-Joseph',
                'lieu_ecole': 'Liège',
                'nom_parent': 'Simon',
                'prenom_parent': 'Farida',
                'nom_enfant': 'Simon',
                'prenom_enfant': 'Adam',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Éducateur',
                'motif_plainte': 'Plainte concernant une situation relationnelle entre élèves.',
                'personne_traitant_dossier': 'Agent Bernard',
                'statut': Plainte.STATUT_EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'En attente d’informations complémentaires.',
            },
            {
                'numero_dossier': 'DOS-2026-009',
                'numero_fase': 'FASE-1009',
                'canal_utilise': 'Email',
                'nom_ecole': 'Athénée Royal Centre',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Rousseau',
                'prenom_parent': 'Mehdi',
                'nom_enfant': 'Rousseau',
                'prenom_enfant': 'Inès',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le traitement administratif d’une demande.',
                'personne_traitant_dossier': 'Gestionnaire Leroy',
                'statut': Plainte.STATUT_TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Réponse envoyée au parent.',
            },
            {
                'numero_dossier': 'DOS-2026-010',
                'numero_fase': 'FASE-1010',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'École Les Érables',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Garcia',
                'prenom_parent': 'Elena',
                'nom_enfant': 'Garcia',
                'prenom_enfant': 'Sofia',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Secrétariat',
                'motif_plainte': 'Plainte concernant une erreur dans les coordonnées du dossier.',
                'personne_traitant_dossier': 'Agent Dubois',
                'statut': Plainte.STATUT_ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Correction effectuée.',
            },
            {
                'numero_dossier': 'DOS-2026-011',
                'numero_fase': 'FASE-1011',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Collège du Midi',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Diallo',
                'prenom_parent': 'Moussa',
                'nom_enfant': 'Diallo',
                'prenom_enfant': 'Awa',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une décision communiquée tardivement.',
                'personne_traitant_dossier': 'Gestionnaire Fontaine',
                'statut': Plainte.STATUT_NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'À analyser.',
            },
            {
                'numero_dossier': 'DOS-2026-012',
                'numero_fase': 'FASE-1012',
                'canal_utilise': 'Email',
                'nom_ecole': 'École Victor Hugo',
                'lieu_ecole': 'Liège',
                'nom_parent': 'Nguyen',
                'prenom_parent': 'Lan',
                'nom_enfant': 'Nguyen',
                'prenom_enfant': 'Tom',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant un manque d’information sur les évaluations.',
                'personne_traitant_dossier': 'Agent Laurent',
                'statut': Plainte.STATUT_EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'Contact prévu avec l’école.',
            },
            {
                'numero_dossier': 'DOS-2026-013',
                'numero_fase': 'FASE-1013',
                'canal_utilise': 'Téléphone',
                'nom_ecole': 'Institut Sainte-Claire',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Peeters',
                'prenom_parent': 'Luc',
                'nom_enfant': 'Peeters',
                'prenom_enfant': 'Mila',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Éducateur',
                'motif_plainte': 'Plainte concernant la prise en charge d’un incident.',
                'personne_traitant_dossier': 'Gestionnaire Mercier',
                'statut': Plainte.STATUT_EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'Documents attendus.',
            },
            {
                'numero_dossier': 'DOS-2026-014',
                'numero_fase': 'FASE-1014',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'École du Canal',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Janssens',
                'prenom_parent': 'Sarah',
                'nom_enfant': 'Janssens',
                'prenom_enfant': 'Elias',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une absence de retour à une demande écrite.',
                'personne_traitant_dossier': 'Agent Martin',
                'statut': Plainte.STATUT_TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Dossier clôturé.',
            },
            {
                'numero_dossier': 'DOS-2026-015',
                'numero_fase': 'FASE-1015',
                'canal_utilise': 'Email',
                'nom_ecole': 'Athénée des Sciences',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Boukhalfa',
                'prenom_parent': 'Samira',
                'nom_enfant': 'Boukhalfa',
                'prenom_enfant': 'Rayan',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Secrétariat',
                'motif_plainte': 'Plainte concernant la transmission d’un document.',
                'personne_traitant_dossier': 'Gestionnaire Petit',
                'statut': Plainte.STATUT_NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Demande à vérifier.',
            },
            {
                'numero_dossier': 'DOS-2026-016',
                'numero_fase': 'FASE-1016',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'École Saint-Martin',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Kaya',
                'prenom_parent': 'Deniz',
                'nom_enfant': 'Kaya',
                'prenom_enfant': 'Leyla',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une inscription administrative.',
                'personne_traitant_dossier': 'Agent Robert',
                'statut': Plainte.STATUT_EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'Vérification avec l’établissement.',
            },
            {
                'numero_dossier': 'DOS-2026-017',
                'numero_fase': 'FASE-1017',
                'canal_utilise': 'Téléphone',
                'nom_ecole': 'Institut Horizon',
                'lieu_ecole': 'Liège',
                'nom_parent': 'Costa',
                'prenom_parent': 'Paulo',
                'nom_enfant': 'Costa',
                'prenom_enfant': 'Mateo',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant une incompréhension sur une sanction.',
                'personne_traitant_dossier': 'Gestionnaire Simon',
                'statut': Plainte.STATUT_EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'En attente de l’avis de l’école.',
            },
            {
                'numero_dossier': 'DOS-2026-018',
                'numero_fase': 'FASE-1018',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'École Les Lilas',
                'lieu_ecole': 'Namur',
                'nom_parent': 'De Smet',
                'prenom_parent': 'Julie',
                'nom_enfant': 'De Smet',
                'prenom_enfant': 'Arthur',
                'genre_enfant': Plainte.GENRE_MASCULIN,
                'personnel_concerne': 'Éducateur',
                'motif_plainte': 'Plainte concernant l’encadrement pendant une activité scolaire.',
                'personne_traitant_dossier': 'Agent Lefort',
                'statut': Plainte.STATUT_TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Explications transmises.',
            },
            {
                'numero_dossier': 'DOS-2026-019',
                'numero_fase': 'FASE-1019',
                'canal_utilise': 'Email',
                'nom_ecole': 'Collège Albert Ier',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Haddad',
                'prenom_parent': 'Nour',
                'nom_enfant': 'Haddad',
                'prenom_enfant': 'Maya',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant un changement d’horaire non communiqué.',
                'personne_traitant_dossier': 'Gestionnaire Dubois',
                'statut': Plainte.STATUT_ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Plainte archivée après réponse.',
            },
            {
                'numero_dossier': 'DOS-2026-020',
                'numero_fase': 'FASE-1020',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'École Nouvelle',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Vandamme',
                'prenom_parent': 'Olivier',
                'nom_enfant': 'Vandamme',
                'prenom_enfant': 'Chloé',
                'genre_enfant': Plainte.GENRE_FEMININ,
                'personnel_concerne': 'Secrétariat',
                'motif_plainte': 'Plainte concernant une attestation scolaire.',
                'personne_traitant_dossier': 'Agent Renard',
                'statut': Plainte.STATUT_NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'À traiter prochainement.',
            },
        ]

        compteur = 0
        for plainte in plaintes:
            objet, cree = Plainte.objects.get_or_create(
                numero_dossier=plainte['numero_dossier'],
                defaults=plainte,
            )
            if cree:
                compteur += 1

        self.stdout.write(self.style.SUCCESS(f'{compteur} plainte(s) fictive(s) créée(s).'))
