from django.core.management.base import BaseCommand

from plaintes.models import Plainte


class Command(BaseCommand):
    help = 'CrÃ©e des plaintes fictives pour tester lâ€™application.'

    def handle(self, *args, **options):
        plaintes = [
            {
                'numero_dossier': 'DOS-2026-001',
                'numero_fase': 'FASE-1001',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Ã‰cole communale du Centre',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Dupont',
                'prenom_parent': 'Marie',
                'nom_enfant': 'Dupont',
                'prenom_enfant': 'Lucas',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le suivi administratif du dossier.',
                'personne_traitant_dossier': 'Lucas',
                'statut': Plainte.Statut.NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Dossier fictif pour test.',
            },
            {
                'numero_dossier': 'DOS-2026-002',
                'numero_fase': 'FASE-1002',
                'canal_utilise': 'Email',
                'nom_ecole': 'Institut Saint-Pierre',
                'lieu_ecole': 'LiÃ¨ge',
                'nom_parent': 'Martin',
                'prenom_parent': 'Sophie',
                'nom_enfant': 'Martin',
                'prenom_enfant': 'Emma',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant une communication insuffisante avec les parents.',
                'personne_traitant_dossier': 'Maurice',
                'statut': Plainte.Statut.EN_COURS,
                'retour_wf_signe': True,
                'remarque': 'Ã€ vÃ©rifier avec la direction.',
            },
            {
                'numero_dossier': 'DOS-2026-003',
                'numero_fase': 'FASE-1003',
                'canal_utilise': 'TÃ©lÃ©phone',
                'nom_ecole': 'AthÃ©nÃ©e Royal Nord',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Bernard',
                'prenom_parent': 'Ahmed',
                'nom_enfant': 'Bernard',
                'prenom_enfant': 'Nora',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Ã‰ducateur',
                'motif_plainte': 'Plainte concernant un incident survenu pendant la rÃ©crÃ©ation.',
                'personne_traitant_dossier': 'Nadine',
                'statut': Plainte.Statut.EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'Attente de documents complÃ©mentaires.',
            },
            {
                'numero_dossier': 'DOS-2026-004',
                'numero_fase': 'FASE-1004',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Ã‰cole Les Tilleuls',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Lambert',
                'prenom_parent': 'Claire',
                'nom_enfant': 'Lambert',
                'prenom_enfant': 'Hugo',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'SecrÃ©tariat',
                'motif_plainte': 'Plainte relative Ã  une erreur dans un document scolaire.',
                'personne_traitant_dossier': 'Maurice',
                'statut': Plainte.Statut.TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Dossier traitÃ©.',
            },
            {
                'numero_dossier': 'DOS-2026-005',
                'numero_fase': 'FASE-1005',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'CollÃ¨ge Sainte-Marie',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Petit',
                'prenom_parent': 'Nadia',
                'nom_enfant': 'Petit',
                'prenom_enfant': 'Yanis',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le dÃ©lai de rÃ©ponse Ã  une demande parentale.',
                'personne_traitant_dossier': 'Nadine',
                'statut': Plainte.Statut.ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Archive fictive.',
            },
            {
                'numero_dossier': 'DOS-2026-006',
                'numero_fase': 'FASE-1006',
                'canal_utilise': 'Email',
                'nom_ecole': 'Ã‰cole du Parc',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Morel',
                'prenom_parent': 'Julien',
                'nom_enfant': 'Morel',
                'prenom_enfant': 'Lina',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une difficultÃ© de communication avec lâ€™Ã©tablissement.',
                'personne_traitant_dossier': 'Agent Dupuis',
                'statut': Plainte.Statut.NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Nouvelle plainte fictive.',
            },
            {
                'numero_dossier': 'DOS-2026-007',
                'numero_fase': 'FASE-1007',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Institut Notre-Dame',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Lefevre',
                'prenom_parent': 'AmÃ©lie',
                'nom_enfant': 'Lefevre',
                'prenom_enfant': 'Noah',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant le suivi pÃ©dagogique de lâ€™enfant.',
                'personne_traitant_dossier': 'Gestionnaire Moreau',
                'statut': Plainte.Statut.EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'Analyse du dossier en cours.',
            },
            {
                'numero_dossier': 'DOS-2026-008',
                'numero_fase': 'FASE-1008',
                'canal_utilise': 'TÃ©lÃ©phone',
                'nom_ecole': 'Ã‰cole Saint-Joseph',
                'lieu_ecole': 'LiÃ¨ge',
                'nom_parent': 'Simon',
                'prenom_parent': 'Farida',
                'nom_enfant': 'Simon',
                'prenom_enfant': 'Adam',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Ã‰ducateur',
                'motif_plainte': 'Plainte concernant une situation relationnelle entre Ã©lÃ¨ves.',
                'personne_traitant_dossier': 'Agent Bernard',
                'statut': Plainte.Statut.EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'En attente dâ€™informations complÃ©mentaires.',
            },
            {
                'numero_dossier': 'DOS-2026-009',
                'numero_fase': 'FASE-1009',
                'canal_utilise': 'Email',
                'nom_ecole': 'AthÃ©nÃ©e Royal Centre',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Rousseau',
                'prenom_parent': 'Mehdi',
                'nom_enfant': 'Rousseau',
                'prenom_enfant': 'InÃ¨s',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant le traitement administratif dâ€™une demande.',
                'personne_traitant_dossier': 'Gestionnaire Leroy',
                'statut': Plainte.Statut.TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'RÃ©ponse envoyÃ©e au parent.',
            },
            {
                'numero_dossier': 'DOS-2026-010',
                'numero_fase': 'FASE-1010',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'Ã‰cole Les Ã‰rables',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Garcia',
                'prenom_parent': 'Elena',
                'nom_enfant': 'Garcia',
                'prenom_enfant': 'Sofia',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'SecrÃ©tariat',
                'motif_plainte': 'Plainte concernant une erreur dans les coordonnÃ©es du dossier.',
                'personne_traitant_dossier': 'Agent Dubois',
                'statut': Plainte.Statut.ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Correction effectuÃ©e.',
            },
            {
                'numero_dossier': 'DOS-2026-011',
                'numero_fase': 'FASE-1011',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'CollÃ¨ge du Midi',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Diallo',
                'prenom_parent': 'Moussa',
                'nom_enfant': 'Diallo',
                'prenom_enfant': 'Awa',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une dÃ©cision communiquÃ©e tardivement.',
                'personne_traitant_dossier': 'Gestionnaire Fontaine',
                'statut': Plainte.Statut.NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Ã€ analyser.',
            },
            {
                'numero_dossier': 'DOS-2026-012',
                'numero_fase': 'FASE-1012',
                'canal_utilise': 'Email',
                'nom_ecole': 'Ã‰cole Victor Hugo',
                'lieu_ecole': 'LiÃ¨ge',
                'nom_parent': 'Nguyen',
                'prenom_parent': 'Lan',
                'nom_enfant': 'Nguyen',
                'prenom_enfant': 'Tom',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant un manque dâ€™information sur les Ã©valuations.',
                'personne_traitant_dossier': 'Agent Laurent',
                'statut': Plainte.Statut.EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'Contact prÃ©vu avec lâ€™Ã©cole.',
            },
            {
                'numero_dossier': 'DOS-2026-013',
                'numero_fase': 'FASE-1013',
                'canal_utilise': 'TÃ©lÃ©phone',
                'nom_ecole': 'Institut Sainte-Claire',
                'lieu_ecole': 'Namur',
                'nom_parent': 'Peeters',
                'prenom_parent': 'Luc',
                'nom_enfant': 'Peeters',
                'prenom_enfant': 'Mila',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Ã‰ducateur',
                'motif_plainte': 'Plainte concernant la prise en charge dâ€™un incident.',
                'personne_traitant_dossier': 'Gestionnaire Mercier',
                'statut': Plainte.Statut.EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'Documents attendus.',
            },
            {
                'numero_dossier': 'DOS-2026-014',
                'numero_fase': 'FASE-1014',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Ã‰cole du Canal',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Janssens',
                'prenom_parent': 'Sarah',
                'nom_enfant': 'Janssens',
                'prenom_enfant': 'Elias',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une absence de retour Ã  une demande Ã©crite.',
                'personne_traitant_dossier': 'Agent Martin',
                'statut': Plainte.Statut.TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Dossier clÃ´turÃ©.',
            },
            {
                'numero_dossier': 'DOS-2026-015',
                'numero_fase': 'FASE-1015',
                'canal_utilise': 'Email',
                'nom_ecole': 'AthÃ©nÃ©e des Sciences',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Boukhalfa',
                'prenom_parent': 'Samira',
                'nom_enfant': 'Boukhalfa',
                'prenom_enfant': 'Rayan',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'SecrÃ©tariat',
                'motif_plainte': 'Plainte concernant la transmission dâ€™un document.',
                'personne_traitant_dossier': 'Gestionnaire Petit',
                'statut': Plainte.Statut.NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Demande Ã  vÃ©rifier.',
            },
            {
                'numero_dossier': 'DOS-2026-016',
                'numero_fase': 'FASE-1016',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'Ã‰cole Saint-Martin',
                'lieu_ecole': 'Charleroi',
                'nom_parent': 'Kaya',
                'prenom_parent': 'Deniz',
                'nom_enfant': 'Kaya',
                'prenom_enfant': 'Leyla',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant une inscription administrative.',
                'personne_traitant_dossier': 'Agent Robert',
                'statut': Plainte.Statut.EN_COURS,
                'retour_wf_signe': False,
                'remarque': 'VÃ©rification avec lâ€™Ã©tablissement.',
            },
            {
                'numero_dossier': 'DOS-2026-017',
                'numero_fase': 'FASE-1017',
                'canal_utilise': 'TÃ©lÃ©phone',
                'nom_ecole': 'Institut Horizon',
                'lieu_ecole': 'LiÃ¨ge',
                'nom_parent': 'Costa',
                'prenom_parent': 'Paulo',
                'nom_enfant': 'Costa',
                'prenom_enfant': 'Mateo',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Enseignant',
                'motif_plainte': 'Plainte concernant une incomprÃ©hension sur une sanction.',
                'personne_traitant_dossier': 'Gestionnaire Simon',
                'statut': Plainte.Statut.EN_ATTENTE,
                'retour_wf_signe': False,
                'remarque': 'En attente de lâ€™avis de lâ€™Ã©cole.',
            },
            {
                'numero_dossier': 'DOS-2026-018',
                'numero_fase': 'FASE-1018',
                'canal_utilise': 'Courrier',
                'nom_ecole': 'Ã‰cole Les Lilas',
                'lieu_ecole': 'Namur',
                'nom_parent': 'De Smet',
                'prenom_parent': 'Julie',
                'nom_enfant': 'De Smet',
                'prenom_enfant': 'Arthur',
                'genre_enfant': Plainte.Genre.MASCULIN,
                'personnel_concerne': 'Ã‰ducateur',
                'motif_plainte': 'Plainte concernant lâ€™encadrement pendant une activitÃ© scolaire.',
                'personne_traitant_dossier': 'Agent Lefort',
                'statut': Plainte.Statut.TRAITEE,
                'retour_wf_signe': True,
                'remarque': 'Explications transmises.',
            },
            {
                'numero_dossier': 'DOS-2026-019',
                'numero_fase': 'FASE-1019',
                'canal_utilise': 'Email',
                'nom_ecole': 'CollÃ¨ge Albert Ier',
                'lieu_ecole': 'Bruxelles',
                'nom_parent': 'Haddad',
                'prenom_parent': 'Nour',
                'nom_enfant': 'Haddad',
                'prenom_enfant': 'Maya',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'Direction',
                'motif_plainte': 'Plainte concernant un changement dâ€™horaire non communiquÃ©.',
                'personne_traitant_dossier': 'Gestionnaire Dubois',
                'statut': Plainte.Statut.ARCHIVEE,
                'retour_wf_signe': True,
                'remarque': 'Plainte archivÃ©e aprÃ¨s rÃ©ponse.',
            },
            {
                'numero_dossier': 'DOS-2026-020',
                'numero_fase': 'FASE-1020',
                'canal_utilise': 'Guichet',
                'nom_ecole': 'Ã‰cole Nouvelle',
                'lieu_ecole': 'Mons',
                'nom_parent': 'Vandamme',
                'prenom_parent': 'Olivier',
                'nom_enfant': 'Vandamme',
                'prenom_enfant': 'ChloÃ©',
                'genre_enfant': Plainte.Genre.FEMININ,
                'personnel_concerne': 'SecrÃ©tariat',
                'motif_plainte': 'Plainte concernant une attestation scolaire.',
                'personne_traitant_dossier': 'Agent Renard',
                'statut': Plainte.Statut.NOUVELLE,
                'retour_wf_signe': False,
                'remarque': 'Ã€ traiter prochainement.',
            },
        ]

        compteur = 0
        for plainte in plaintes:
            objet, cree = Plainte.objects.get_or_create(
                numero_dossier=plainte['numero_dossier'],
                defaults=plainte,
            )
            if cree:
                compteur += 1

        self.stdout.write(self.style.SUCCESS(f'{compteur} plainte(s) fictive(s) crÃ©Ã©e(s).'))

